- name: "Ports should be {{ task.want_state }}."
  wait_for:
    host: "{{ inventory_hostname }}"
    port: "{{ port }}"
    timeout: "{{ task.timeout }}"
    state: "{{ task.want_state }}"
  delegate_to: "{{ task.remote }}"
  loop: "{{ task.ports }}"
  loop_control:
    loop_var: port
