- name: "Ports should be {{ task.want_state }}."
  wait_for:
    port: "{{ port }}"
    timeout: "{{ task.timeout }}"
    state: "{{ task.want_state }}"
    host: "127.0.0.1"
  loop: "{{ task.ports }}"
  loop_control:
    loop_var: port
