- name: "Checking.."
  wait_for:
    host: "{{ task.remote }}"
    port: "{{ port }}"
    timeout: "{{ task.timeout }}"
    state: "{{ task.want_state }}"
  loop: "{{ task.ports }}"
  loop_control:
    loop_var: port

